// Publishing to WordPress with nothing installed on the customer's site.
//
// The plugin route (/wp-json/itgrows/v1/publish) still exists and is still the fallback, but it
// makes every WordPress customer install something before a single article can ship. An
// Application Password is generated by the customer in their own profile in about a minute and
// works against the standard REST API.
//
// Lives here rather than in a route because two callers need it — the publish endpoint and the
// scheduled-publishing cron, which does not go through that endpoint.

export interface WpArticle {
  title: string
  content: string
  metaDescription?: string | null
  slug: string
  coverImageUrl?: string | null
}

export interface WpResult {
  success: boolean
  url?: string
  postId?: number
  cover: "attached" | "skipped"
  error?: string
}

export function canUseAppPassword(site: {
  platform?: string | null
  wpUsername?: string | null
  wpAppPassword?: string | null
}): boolean {
  return site.platform === "wordpress" && !!site.wpUsername?.trim() && !!site.wpAppPassword?.trim()
}

/** Upload the cover to the media library. Best effort — never blocks the article. */
async function uploadCover(base: string, auth: string, article: WpArticle): Promise<number | undefined> {
  if (!article.coverImageUrl) return undefined
  try {
    const imgRes = await fetch(article.coverImageUrl, { signal: AbortSignal.timeout(20000) })
    if (!imgRes.ok) return undefined

    const bytes = await imgRes.arrayBuffer()
    const type = imgRes.headers.get("content-type") ?? "image/jpeg"
    const ext = type.includes("png") ? "png" : type.includes("webp") ? "webp" : "jpg"

    const mediaRes = await fetch(`${base}/media`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": type,
        "Content-Disposition": `attachment; filename="${article.slug}.${ext}"`,
      },
      body: Buffer.from(bytes),
      signal: AbortSignal.timeout(30000),
    })

    if (!mediaRes.ok) {
      console.warn(`[wp] media upload ${mediaRes.status} — publishing without a cover`)
      return undefined
    }
    const media = (await mediaRes.json()) as { id?: number }
    return media.id
  } catch (err) {
    // A cover is part of what we sell, so this is worth a log line rather than a silent pass —
    // but losing it must never cost the article.
    console.warn("[wp] media upload failed — publishing without a cover:", err)
    return undefined
  }
}

export async function publishToWordPress(
  siteUrl: string,
  username: string,
  appPassword: string,
  article: WpArticle
): Promise<WpResult> {
  let normalUrl = siteUrl.trim().replace(/\/$/, "")
  if (!normalUrl.startsWith("http")) normalUrl = "https://" + normalUrl
  const base = `${normalUrl}/wp-json/wp/v2`

  // WordPress prints the password in spaced groups and accepts either form; trimming guards
  // against a newline picked up in a paste.
  const auth = Buffer.from(`${username.trim()}:${appPassword.trim()}`).toString("base64")

  const featuredMedia = await uploadCover(base, auth, article)

  try {
    const res = await fetch(`${base}/posts`, {
      method: "POST",
      headers: { Authorization: `Basic ${auth}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        title: article.title,
        content: article.content,
        excerpt: article.metaDescription ?? "",
        slug: article.slug,
        status: "publish",
        ...(featuredMedia ? { featured_media: featuredMedia } : {}),
      }),
      signal: AbortSignal.timeout(20000),
    })

    if (!res.ok) {
      const errText = await res.text().catch(() => "")
      // 401/403 here is nearly always a revoked or mistyped application password. Say so, rather
      // than handing back a bare status for someone to decode.
      const hint =
        res.status === 401 || res.status === 403
          ? " (check the WordPress username and application password)"
          : ""
      return {
        success: false,
        cover: featuredMedia ? "attached" : "skipped",
        error: `WordPress returned ${res.status}${hint}: ${errText.slice(0, 300)}`,
      }
    }

    const data = (await res.json()) as { id?: number; link?: string }
    return {
      success: true,
      url: data.link ?? normalUrl,
      postId: data.id,
      cover: featuredMedia ? "attached" : "skipped",
    }
  } catch (err) {
    return {
      success: false,
      cover: featuredMedia ? "attached" : "skipped",
      error: err instanceof Error ? err.message : "WordPress publish failed",
    }
  }
}
